apiVersion: v1
kind: Service
metadata:
  name: eap-metrics
spec:
  ports:
    - port: 8998
      protocol: TCP
      targetPort: 8998
  selector:
    deploymentConfig: eap-app
  sessionAffinity: None
  type: ClusterIP
