apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '9404'
    prometheus.io/scrape: 'true'
  name: prometheus-metrics
spec:
  ports:
    - port: 9404
      protocol: TCP
      targetPort: 9404
  selector:
    app: app
    deploymentconfig: app
  sessionAffinity: None
  type: ClusterIP
